version: "3.7"

services:
    web:
        build:
            context: docker
        links:
            - db
            - mailhog
        volumes:
            - ".:/www"
        expose:
            - "9000"
        extra_hosts:
            - "local.intranet.opt:127.0.0.1"
        environment:
            - DOMAIN_ROOT_DIR=/www/web

    nginx:
        image: nginx
        depends_on:
            - web
        links:
            - web
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "web:/www"
            - "./docker/config/nginx.conf:/etc/nginx/conf.d/default.conf"
            - "./docker/certificates/certificate.pem:/etc/ssl/certs/certificate.pem"
            - "./docker/certificates/certificate.key:/etc/ssl/private/certificate.key"

    db:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root

    pma:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - db
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: root

    mailhog:
        #container_name: mailhog
        image: mailhog/mailhog
        ports:
            - "1025:1025"
            - "8025:8025"

volumes:
    web:
